import { put } from "@vercel/blob";
import { after, type NextRequest } from "next/server";
import { readSession } from "./auth";
import { query } from "./db";
import { sendBookingNotificationEmailSafe } from "./email";
import { body, json } from "./http";

const parse=(v:any,f:any)=>{try{return typeof v==="string"?JSON.parse(v):v??f}catch{return f}};
export async function agentPricing(request:NextRequest){
  if(request.method==="GET"){const setting=(await query<any>("SELECT setting_value FROM site_settings WHERE setting_key='agent_pricing'")).rows[0];const boats=await query<any>("SELECT id,price FROM boat_types WHERE is_active=1 ORDER BY sort_order,id");const payments=(await query<any>("SELECT setting_value FROM site_settings WHERE setting_key='payment_settings'")).rows[0];return json({agent_pricing:setting?parse(setting.setting_value,{enabled:false}):{enabled:false},normal_prices:Object.fromEntries(boats.rows.map((x:any)=>[x.id,Number(x.price)])),payment_settings:payments?parse(payments.setting_value,{}):{}});}
  if(request.method!=="POST")return json({error:"Method not allowed"},405);if(!(await readSession(request,"admin")))return json({error:"Unauthorized"},401);const input=await body(request);const row=(await query<any>("SELECT setting_value FROM site_settings WHERE setting_key='agent_pricing'")).rows[0];const value=row?parse(row.setting_value,{enabled:false}):{enabled:false};if(Object.hasOwn(input,"enabled"))value.enabled=Boolean(input.enabled);for(const [key,item] of Object.entries<any>(input))if(key!=="enabled"&&item&&Object.hasOwn(item,"price"))value[key]={price:Number(item.price)};await query("INSERT INTO site_settings(setting_key,setting_value) VALUES('agent_pricing',$1) ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,updated_at=NOW()",[JSON.stringify(value)]);return json({success:true,agent_pricing:value});
}

export async function agentSlip(request:NextRequest){
  if(request.method==="POST"){
    const session=await readSession(request,"agent");if(!session)return json({error:"ไม่มีสิทธิ์: กรุณาเข้าสู่ระบบ agent"},401);const form=await request.formData();const bookingId=String(form.get("booking_id")||"").trim();const file=form.get("slip");if(!bookingId)return json({error:"กรุณาระบุ booking_id"},400);if(!(file instanceof File))return json({error:"กรุณาเลือกไฟล์ slip"},400);if(file.size>5*1024*1024)return json({error:"ไฟล์ใหญ่เกิน 5MB"},400);if(!["image/jpeg","image/png","image/webp","image/gif"].includes(file.type))return json({error:"รองรับเฉพาะ JPG, PNG, WebP, GIF"},400);const booking=(await query<any>("SELECT total_price FROM bookings WHERE booking_id=$1 AND agent_id=$2",[bookingId,session.id])).rows[0];if(!booking)return json({error:"ไม่พบการจองนี้หรือไม่ใช่การจองของคุณ"},404);const blob=await put(`slips/${bookingId}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`,file,{access:"public",addRandomSuffix:true});await query("INSERT INTO agent_payment_slips(booking_id,agent_id,slip_url,amount,status) VALUES($1,$2,$3,$4,'pending')",[bookingId,session.id,blob.url,Number(form.get("amount")||booking.total_price)]);await query("UPDATE bookings SET payment_method='bank_transfer' WHERE booking_id=$1",[bookingId]);return json({success:true,slip_url:blob.url,message:"อัปโหลด slip สำเร็จ กรุณารอการยืนยันจาก admin"},201);
  }
  const admin=await readSession(request,"admin");if(!admin)return json({error:"Unauthorized"},401);
  if(request.method==="GET"){const status=new URL(request.url).searchParams.get("status");const values=status?[status]:[];const slips=await query<any>(`SELECT s.*,b.boat_type,b.booking_date,b.time_slot,b.customer_name,b.customer_phone,b.total_price booking_price,a.first_name||' '||a.last_name agent_name,a.company agent_company FROM agent_payment_slips s JOIN bookings b ON s.booking_id=b.booking_id JOIN agents a ON s.agent_id=a.id ${status?"WHERE s.status=$1":""} ORDER BY s.created_at DESC`,values);const counts=await query<any>("SELECT status,COUNT(*)::int cnt FROM agent_payment_slips GROUP BY status");return json({slips:slips.rows,counts:{pending:0,approved:0,rejected:0,...Object.fromEntries(counts.rows.map((x:any)=>[x.status,x.cnt]))}});}
  if(request.method==="PUT"){const input=await body(request);if(!["approved","rejected"].includes(input.status))return json({error:"Status must be approved or rejected"},400);const slip=(await query<any>("SELECT booking_id FROM agent_payment_slips WHERE id=$1",[input.id])).rows[0];if(!slip)return json({error:"Slip not found"},404);await query("UPDATE agent_payment_slips SET status=$1,admin_note=$2,updated_at=NOW() WHERE id=$3",[input.status,input.note||null,input.id]);const bookingUpdate=await query<any>("UPDATE bookings SET status=$1,payment_method=CASE WHEN $1='confirmed' AND COALESCE(payment_method,'')='' THEN 'bank_transfer' WHEN $1='confirmed' THEN payment_method ELSE '' END WHERE booking_id=$2 RETURNING booking_id,booking_date::text,time_slot,boat_type,customer_name,customer_phone,customer_email,payment_method,total_price",[input.status==="approved"?"confirmed":"pending",slip.booking_id]);const booking=bookingUpdate.rows[0];if(input.status==="approved"&&booking){after(()=>sendBookingNotificationEmailSafe({bookingId:String(booking.booking_id),bookingDate:String(booking.booking_date).slice(0,10),timeSlot:String(booking.time_slot),boatType:String(booking.boat_type),customerName:String(booking.customer_name||""),customerPhone:String(booking.customer_phone||""),customerEmail:String(booking.customer_email||""),paymentMethod:String(booking.payment_method||"bank_transfer"),totalPrice:Number(booking.total_price||0)}));}return json({success:true,message:"อัปเดตสถานะ slip สำเร็จ",email_queued:input.status==="approved"});}
  return json({error:"Method not allowed"},405);
}

export async function agentBooking(request:NextRequest){
  const session=await readSession(request,"agent");if(!session)return json({error:"ไม่มีสิทธิ์: กรุณาเข้าสู่ระบบ agent"},401);
  if(request.method==="GET"){const r=await query<any>("SELECT booking_id,boat_type,booking_date,time_slot,guests,customer_name,customer_phone,total_price,status,created_at FROM bookings WHERE agent_id=$1 ORDER BY created_at DESC LIMIT 50",[session.id]);return json({success:true,bookings:r.rows});}
  const input=await body(request);
  if(request.method==="PUT"){const booking=(await query<any>("SELECT id,status FROM bookings WHERE booking_id=$1 AND agent_id=$2",[input.booking_id,session.id])).rows[0];if(!booking)return json({error:"ไม่พบการจอง หรือไม่มีสิทธิ์"},404);if(booking.status!=="pending")return json({error:"ไม่สามารถยกเลิกการจองนี้ได้ กรุณาติดต่อ admin"},400);await query("UPDATE bookings SET status='cancelled' WHERE id=$1",[booking.id]);return json({success:true,message:"ยกเลิกการจองเรียบร้อยแล้ว"});}
  if(request.method!=="POST")return json({error:"Method not allowed"},405);for(const field of ["boat_type","booking_date","time_slot","guests","customer_name","customer_phone"])if(!input[field])return json({error:`กรุณากรอก: ${field}`},400);if(String(input.booking_date)<new Date().toISOString().slice(0,10))return json({error:"ไม่สามารถจองวันที่ผ่านมาแล้วได้"},400);
  const boat=(await query<any>("SELECT total_boats,price FROM boat_types WHERE id=$1 AND is_active=1",[input.boat_type])).rows[0];if(!boat)return json({error:"ประเภทเรือไม่ถูกต้องหรือไม่ได้เปิดใช้งาน"},400);const over=(await query<any>("SELECT status,total_boats,blocked_boats FROM boat_availability WHERE boat_type=$1 AND slot_date=$2 AND time_slot=$3",[input.boat_type,input.booking_date,input.time_slot])).rows[0];if(over?.status==="blocked")return json({error:"สล็อตนี้ถูกบล็อค กรุณาเลือกวันหรือรอบอื่น"},409);const booked=Number((await query<any>("SELECT COUNT(*)::int cnt FROM bookings WHERE boat_type=$1 AND booking_date=$2 AND time_slot=$3 AND status!='cancelled'",[input.boat_type,input.booking_date,input.time_slot])).rows[0].cnt);if(Number(over?.total_boats??boat.total_boats)-booked-Number(over?.blocked_boats||0)<=0)return json({error:"เรือเต็มแล้ว กรุณาเลือกวันหรือรอบอื่น"},409);
  const priceRow=(await query<any>("SELECT setting_value FROM site_settings WHERE setting_key='agent_pricing'")).rows[0];const pricing=priceRow?parse(priceRow.setting_value,{enabled:false}):{enabled:false};const useAgentPrice=Boolean(pricing.enabled);const price=useAgentPrice?Number(pricing[input.boat_type]?.price??boat.price):Number(boat.price);const id=`AG-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${String(Math.floor(Math.random()*999)+1).padStart(3,"0")}`;await query("INSERT INTO bookings(booking_id,boat_type,booking_date,time_slot,guests,customer_name,customer_phone,customer_email,payment_method,total_price,status,notes,agent_id,agent_price,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'',$9,'pending',$10,$11,$12,'agent')",[id,input.boat_type,input.booking_date,input.time_slot,Number(input.guests),input.customer_name,input.customer_phone,input.customer_email||"",price,input.notes||`จองโดย agent: ${session.name}`,session.id,useAgentPrice?price:null]);return json({success:true,booking_id:id,total_price:price,agent_price:useAgentPrice,message:"สร้างการจองสำเร็จ"},201);
}
