import { del, put } from "@vercel/blob";
import type { NextRequest } from "next/server";
import { createPasswordHash, readSession, verifyPassword } from "./auth";
import { body, json, publicJson } from "./http";
import { prisma } from "./prisma";

async function setting(key:string,fallback:any[]=[]){const row=await prisma.siteSetting.findUnique({where:{settingKey:key}});if(!row)return fallback;try{return JSON.parse(row.settingValue)}catch{return fallback}}
async function save(key:string,value:any){await prisma.siteSetting.upsert({where:{settingKey:key},create:{settingKey:key,settingValue:JSON.stringify(value)},update:{settingValue:JSON.stringify(value)}})}
export async function galleryAuth(request:NextRequest){if(request.method!=="POST")return json({error:"Method not allowed"},405);const input=await body(request);const folders=await setting("gallery_folders");const folder=folders.find((x:any)=>x.id===input.folder_id);if(!folder)return json({error:"ไม่พบอัลบั้มนี้"},404);if(!(await verifyPassword(String(input.password||""),folder.password)))return json({error:"รหัสผ่านไม่ถูกต้อง"},401);const items=await setting("gallery_items");return json({success:true,folder:{id:folder.id,name:folder.name},items:items.filter((x:any)=>x.folder_id===folder.id)});}
export async function gallery(request:NextRequest){
  let items=await setting("gallery_items"),folders=await setting("gallery_folders");const admin=await readSession(request,"admin");const url=new URL(request.url);
  if(request.method==="GET"){if(url.searchParams.has("admin")){if(!admin)return json({error:"Unauthorized"},401);return json({items,folders});}return publicJson({items:items.filter((x:any)=>!x.folder_id),folders:folders.map((x:any)=>({id:x.id,name:x.name,created_at:x.created_at})).sort((a:any,b:any)=>String(b.created_at).localeCompare(String(a.created_at)))});}
  if(!admin)return json({error:"Unauthorized"},401);
  if(request.method==="POST"){
    const contentType=request.headers.get("content-type")||"";
    if(contentType.includes("application/json")){const input=await body(request);const match=String(input.youtube_url||"").match(/(?:youtube\.com\/(?:watch\?v=|shorts\/|embed\/)|youtu\.be\/)([a-zA-Z0-9_-]{11})/);if(!match)return json({error:"ไม่พบ YouTube Video ID กรุณาตรวจสอบ URL"},400);const item={id:`yt_${crypto.randomUUID()}`,type:"youtube",youtube_id:match[1],src:`https://img.youtube.com/vi/${match[1]}/hqdefault.jpg`,caption:input.caption||"",event_date:input.event_date||new Date().toISOString().slice(0,10),folder_id:input.folder_id||"",uploaded_at:new Date().toISOString()};items.unshift(item);await save("gallery_items",items);return json({success:true,item});}
    const form=await request.formData();if(form.get("action")==="create_folder"){const name=String(form.get("name")||"").trim(),password=String(form.get("password")||"");if(!name||!password)return json({error:"กรุณาระบุชื่ออัลบั้มและรหัสผ่าน"},400);const folder={id:`fld_${crypto.randomUUID()}`,name,password:await createPasswordHash(password),created_at:new Date().toISOString()};folders.unshift(folder);await save("gallery_folders",folders);return json({success:true,folder:{id:folder.id,name}});}
    const file=form.get("image");if(!(file instanceof File))return json({error:"No file uploaded"},400);if(file.size>10*1024*1024)return json({error:"ไฟล์ใหญ่เกินไป สูงสุด 10MB"},400);if(!["image/jpeg","image/png","image/webp","image/gif"].includes(file.type))return json({error:"ไฟล์ไม่ถูกต้อง"},400);const blob=await put(`gallery/${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`,file,{access:"public",addRandomSuffix:true});const item={id:`gal_${crypto.randomUUID()}`,src:blob.url,caption:String(form.get("caption")||""),event_date:String(form.get("event_date")||new Date().toISOString().slice(0,10)),type:"image",folder_id:String(form.get("folder_id")||""),uploaded_at:new Date().toISOString()};items.unshift(item);await save("gallery_items",items);return json({success:true,item});
  }
  const input=await body(request);
  if(request.method==="DELETE"){if(input.action==="delete_folder"){const removed=items.filter((x:any)=>x.folder_id===input.id);for(const x of removed)if(x.type!=="youtube"&&String(x.src).includes("blob.vercel-storage.com"))await del(x.src);folders=folders.filter((x:any)=>x.id!==input.id);items=items.filter((x:any)=>x.folder_id!==input.id);await save("gallery_folders",folders);await save("gallery_items",items);return json({success:true});}const target=items.find((x:any)=>x.id===input.id);if(!target)return json({error:"Item not found"},404);if(target.type!=="youtube"&&String(target.src).includes("blob.vercel-storage.com"))await del(target.src);items=items.filter((x:any)=>x.id!==input.id);await save("gallery_items",items);return json({success:true});}
  if(request.method==="PUT"){if(input.action==="update_folder_password"){const folder=folders.find((x:any)=>x.id===input.id);if(!folder)return json({error:"Folder not found"},404);folder.password=await createPasswordHash(input.password);await save("gallery_folders",folders);return json({success:true});}const item=items.find((x:any)=>x.id===input.id);if(!item)return json({error:"Item not found"},404);for(const key of ["caption","event_date","folder_id"])if(Object.hasOwn(input,key))item[key]=input[key];await save("gallery_items",items);return json({success:true});}
  return json({error:"Method not allowed"},405);
}
