import type { NextRequest } from "next/server";
import { createHmac, timingSafeEqual } from "node:crypto";
import { query } from "./db";
import { body, json } from "./http";

const escape=(v:any)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
export async function paysolutionsPayment(request:NextRequest){
  const url=new URL(request.url);
  if(request.method==="GET"&&url.searchParams.has("go")){const booking=(await query<any>("SELECT id,booking_id,total_price,customer_email,customer_name,customer_phone FROM bookings WHERE booking_id=$1",[url.searchParams.get("booking_id")])).rows[0];if(!booking)return new Response("Booking not found",{status:404});const base=url.origin;const action=process.env.PAYSO_SANDBOX==="true"?"https://sandbox.thaiepay.com/epaylink/payment.aspx?lang=t":"https://www.thaiepay.com/epaylink/payment.aspx?lang=t";const fields={merchantid:process.env.PAYSO_MERCHANT_ID||"",refno:booking.id,customeremail:booking.customer_email||"",productdetail:`AQUATHRILL Booking ${booking.booking_id}`,total:Number(booking.total_price).toFixed(2),returnurl:`${base}/booking/payment/result.html?booking_id=${encodeURIComponent(booking.booking_id)}`,customername:booking.customer_name||"",customertel:booking.customer_phone||""};const inputs=Object.entries(fields).map(([k,v])=>`<input type="hidden" name="${k}" value="${escape(v)}">`).join("");return new Response(`<!doctype html><html lang="th"><meta charset="utf-8"><title>กำลังเชื่อมต่อ Payso...</title><style>body{margin:0;font-family:sans-serif;background:#0a1628;color:#fff;display:grid;place-items:center;min-height:100vh}.spinner{width:48px;height:48px;border:4px solid #235;border-top-color:#00d4ff;border-radius:50%;animation:s 1s linear infinite}@keyframes s{to{transform:rotate(360deg)}}</style><div><div class="spinner"></div><h2>กำลังเชื่อมต่อระบบชำระเงิน Payso...</h2></div><form id="p" action="${action}" method="post">${inputs}</form><script>document.getElementById('p').submit()</script></html>`,{headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"}});}
  if(request.method!=="POST")return json({error:"Method not allowed"},405);const input=await body(request);if(!input.booking_id)return json({error:"Missing booking_id"},400);if(!process.env.PAYSO_MERCHANT_ID)return json({error:"Payment gateway not configured"},500);const booking=(await query<any>("SELECT booking_id,total_price,status FROM bookings WHERE booking_id=$1",[input.booking_id])).rows[0];if(!booking)return json({error:"Booking not found"},404);if(booking.status==="confirmed")return json({error:"Booking already paid"},400);await query("INSERT INTO payment_logs(booking_id,payment_method,amount,status) VALUES($1,'payso',$2,'pending')",[booking.booking_id,booking.total_price]);return json({success:true,redirect_url:`${new URL(request.url).origin}/api/paysolutions-payment.php?go=1&booking_id=${encodeURIComponent(booking.booking_id)}`});
}

export async function paysolutionsCallback(request:NextRequest){
  if(!["GET","POST"].includes(request.method))return new Response("Method not allowed",{status:405});const url=new URL(request.url);let data:Record<string,any>=Object.fromEntries(url.searchParams);
  if(request.method==="POST"){const ct=request.headers.get("content-type")||"";if(ct.includes("application/json"))data={...data,...await body(request)};else{const text=await request.text();data={...data,...Object.fromEntries(new URLSearchParams(text))};}}
  const refno=String(data.refno||""),tx=String(data.orderno||data.transactionid||"");if(!/^[A-Za-z0-9_-]{1,50}$/.test(refno))return new Response("Invalid refno",{status:400});if(tx&&!/^[A-Za-z0-9_-]{1,50}$/.test(tx))return new Response("Invalid transaction id",{status:400});const booking=(await query<any>("SELECT id,booking_id,total_price,status FROM bookings WHERE id::text=$1 OR booking_id=$1 LIMIT 1",[refno])).rows[0];if(!booking)return new Response("Booking not found",{status:404});if(Number(booking.total_price).toFixed(2)!==Number(data.total).toFixed(2))return new Response("Amount mismatch",{status:400});
  const supplied=String(data.pkey||data.signature||data.auth_token||"");if(supplied&&process.env.PAYSO_SECRET_KEY){const expected=createHmac("sha256",process.env.PAYSO_SECRET_KEY).update(`${refno}|${data.total}|${data.status}|${tx}`).digest("hex");const a=Buffer.from(supplied),b=Buffer.from(expected);if(a.length!==b.length||!timingSafeEqual(a,b))return new Response("Invalid signature",{status:403});}
  if(tx){const replay=await query("SELECT id FROM payment_logs WHERE transaction_id=$1 AND status='completed' LIMIT 1",[tx]);if(replay.rowCount)return new Response("OK");}
  const completed=data.status==="CP";await query("INSERT INTO payment_logs(booking_id,transaction_id,payment_method,amount,status,gateway_response) VALUES($1,$2,'payso',$3,$4,$5::jsonb)",[booking.booking_id,tx||null,booking.total_price,completed?"completed":"failed",JSON.stringify(data)]);if(completed&&booking.status!=="confirmed")await query("UPDATE bookings SET status='confirmed',payment_method='payso' WHERE id=$1",[booking.id]);return new Response("OK",{headers:{"Content-Type":"text/plain; charset=utf-8"}});
}
