import { del, put } from "@vercel/blob";
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { readSession } from "./auth";
import { query } from "./db";
import { body, json } from "./http";

async function googleReviews(){if(!process.env.GOOGLE_API_KEY||!process.env.GOOGLE_PLACE_ID)return null;const params=new URLSearchParams({place_id:process.env.GOOGLE_PLACE_ID,fields:"reviews,rating,user_ratings_total,photos",reviews_sort:"newest",reviews_no_translations:"true",key:process.env.GOOGLE_API_KEY});const response=await fetch(`https://maps.googleapis.com/maps/api/place/details/json?${params}`,{cache:"no-store"});const data=await response.json();if(!response.ok||data.status!=="OK")throw new Error(`Google API error: ${data.status||response.status}`);const result=data.result||{};const placePhotos=(result.photos||[]).slice(0,18).map((p:any)=>p.photo_reference).filter(Boolean).map((ref:string)=>`/api/google-reviews.php?photo_ref=${encodeURIComponent(ref)}`);return {rating:result.rating??null,total_reviews:result.user_ratings_total??null,place_photos:placePhotos,reviews:(result.reviews||[]).map((x:any,i:number)=>({author_name:x.author_name||"",author_photo:x.profile_photo_url||"",rating:x.rating||5,text:x.text||"",time:x.time||0,relative_time:x.relative_time_description||"",language:x.language||"th",source:"google",review_key:`${x.author_name||""}::${x.time||0}`,photos:placePhotos.length?placePhotos.slice(i*3,i*3+5).concat(placePhotos).slice(0,Math.min(5,placePhotos.length)):[]})),cached_at:new Date().toISOString(),expires_at:new Date(Date.now()+86400000).toISOString()};}
async function getCache(){const r=await query<any>("SELECT setting_value FROM site_settings WHERE setting_key='google_reviews_cache'");if(!r.rows[0])return null;try{return JSON.parse(r.rows[0].setting_value)}catch{return null}}
async function saveCache(value:any){await query("INSERT INTO site_settings(setting_key,setting_value) VALUES('google_reviews_cache',$1) ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,updated_at=NOW()",[JSON.stringify(value)])}
export async function reviews(request:NextRequest){
  const url=new URL(request.url),isAdmin=url.searchParams.get("admin")==="1";if(isAdmin&&!(await readSession(request,"admin")))return json({error:"Unauthorized"},401);
  const photoRef=url.searchParams.get("photo_ref");if(request.method==="GET"&&photoRef){if(!process.env.GOOGLE_API_KEY)return json({error:"Google API Key ยังไม่ได้ตั้งค่า"},400);const params=new URLSearchParams({maxwidth:"900",photo_reference:photoRef,key:process.env.GOOGLE_API_KEY});return NextResponse.redirect(`https://maps.googleapis.com/maps/api/place/photo?${params}`,{headers:{"Cache-Control":"public, max-age=86400, s-maxage=604800, stale-while-revalidate=2592000"}});}
  if(request.method==="GET"){let cache=await getCache();if(url.searchParams.get("refresh")==="1"||!cache||new Date(cache.expires_at)<new Date()||!Array.isArray(cache.place_photos)){try{cache=await googleReviews();if(cache)await saveCache(cache)}catch{}}const manual=(await query<any>("SELECT * FROM manual_reviews ORDER BY created_at DESC")).rows.map((x:any)=>({...x,id:Number(x.id),rating:Number(x.rating),enabled:Boolean(x.enabled),source:"manual",relative_time:"เพิ่มโดยแอดมิน"}));const disabled=new Set((await query<any>("SELECT review_key FROM google_reviews_toggle")).rows.map((x:any)=>x.review_key));const google=(cache?.reviews||[]).map((x:any)=>({...x,enabled:!disabled.has(x.review_key)}));if(isAdmin)return json({success:true,source:cache?"cache":"static",cached_at:cache?.cached_at,expires_at:cache?.expires_at,rating:cache?.rating,total_reviews:cache?.total_reviews,place_photos:cache?.place_photos||[],google_reviews:google,manual_reviews:manual});return json({success:true,source:cache?"cache":"static",cached_at:cache?.cached_at,rating:cache?.rating,total_reviews:cache?.total_reviews,place_photos:cache?.place_photos||[],reviews:[...google.filter((x:any)=>x.enabled),...manual.filter((x:any)=>x.enabled)]});}
  if(request.method!=="POST")return json({error:"Method not allowed"},405);if(!(await readSession(request,"admin")))return json({error:"Unauthorized"},401);const ct=request.headers.get("content-type")||"";let input:any,file:File|null=null;if(ct.includes("multipart/form-data")){const form=await request.formData();input=Object.fromEntries(form);file=form.get("photo") instanceof File?form.get("photo") as File:null}else input=await body(request);const action=input.action;
  if(action==="refresh"){const value=await googleReviews();if(!value)return json({success:false,error:"Google API Key หรือ Place ID ยังไม่ได้ตั้งค่า"},400);await saveCache(value);return json({success:true,message:"รีเฟรชรีวิวสำเร็จ",cached_at:value.cached_at,total_reviews:value.total_reviews,reviews_count:value.reviews.length});}
  if(action==="cache_status"){const cache=await getCache();const counts=(await query<any>("SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE enabled=1)::int enabled FROM manual_reviews")).rows[0];return json({success:true,has_cache:!!cache,is_valid:!!cache&&new Date(cache.expires_at)>new Date(),cached_at:cache?.cached_at,expires_at:cache?.expires_at,reviews_count:cache?.reviews?.length||0,manual_count:counts.total,manual_enabled:counts.enabled,rating:cache?.rating,api_configured:!!process.env.GOOGLE_API_KEY&&!!process.env.GOOGLE_PLACE_ID});}
  if(action==="clear_cache"){await query("DELETE FROM site_settings WHERE setting_key='google_reviews_cache'");return json({success:true});}
  if(action==="toggle_review"){if(input.enabled)await query("DELETE FROM google_reviews_toggle WHERE review_key=$1",[input.review_key]);else await query("INSERT INTO google_reviews_toggle(review_key) VALUES($1) ON CONFLICT DO NOTHING",[input.review_key]);return json({success:true});}
  if(action==="toggle_manual"){await query("UPDATE manual_reviews SET enabled=$1 WHERE id=$2",[input.enabled?1:0,input.id]);return json({success:true});}
  if(action==="delete_manual"){const row=(await query<any>("DELETE FROM manual_reviews WHERE id=$1 RETURNING photo",[input.id])).rows[0];if(row?.photo?.includes("blob.vercel-storage.com"))await del(row.photo);return json({success:true});}
  if(["add_manual","edit_manual"].includes(action)){let photo=input.existing_photo||"";if(file){if(file.size>5*1024*1024)return json({error:"File too large"},400);const blob=await put(`reviews/${file.name}`,file,{access:"public",addRandomSuffix:true});photo=blob.url;}if(action==="add_manual"){const r=await query<any>("INSERT INTO manual_reviews(author_name,rating,text,photo,trip,enabled) VALUES($1,$2,$3,$4,$5,1) RETURNING id",[input.author_name,Number(input.rating||5),input.text,photo,input.trip||"Customer Review"]);return json({success:true,id:r.rows[0].id});}await query("UPDATE manual_reviews SET author_name=$1,rating=$2,text=$3,photo=$4,trip=$5 WHERE id=$6",[input.author_name,Number(input.rating||5),input.text,photo,input.trip||"Customer Review",input.id]);return json({success:true});}
  return json({error:"Invalid action"},400);
}
